### DISCUSSION TITLE
Is there a way to have SASS imports relative to the current file?

### DISCUSSION THREAD

**Discussion by dretsa** [web-infra-dev/rsbuild#2764] [Q&A] [answered]
If I were to import a font I need to place it in the `index.scss` directory. Is it possible to enable relative resolving so that I can use the 7-1 SASS pattern and have my assets in a different folder?

Example:
```
- scss
  - index.scss
  - typography
    - _index.scss
    - InterVariable.woff2 
```

```scss
// scss/typography/_index.scss

@font-face {
  font-family: 'Inter';
  src: url(InterVariable.woff2) format('woff2');
  font-weight: 1 999;
  font-style: normal;
  font-display: swap;
}
```
