### DISCUSSION TITLE
scss compilation inconsistent

### DISCUSSION THREAD

**Discussion by liu-collab** [web-infra-dev/rsbuild#3381] [Q&A]
```css  
.form {
  :global {
    .ant-input,
    .ant-btn {
      width: 360px;
      height: 40px;
      margin-left: 0px;
      border-radius: 8px !important;
      font-size: 16px;
    }
  }
}
```
package.json
```json
   "sass": "^1.69.5",
   "sass-loader": "^13.3.2",
   "@rsbuild/core": "^1.0.1-rc.4",
   "@rsbuild/plugin-react": "^1.0.1-rc.4",
   "@rsbuild/plugin-svgr": "^1.0.1-rc.4",
   "@rsbuild/plugin-sass": "^1.0.1-rc.4",
```
webpakck编译后
```css 
.Form_form__93rTd .ant-btn,.Form_form__93rTd .ant-input {
    border-radius: 8px!important;
    font-size: 16px;
    height: 40px;
    margin-left: 0;
    width: 360px
}
```
rspack编译后
```css 
:is(.src-pages-Login-Form-index-module__form-I99lWw .ant-input, .form .ant-btn) {
  width: 360px;
  height: 40px;
  margin-left: 0;
  font-size: 16px;
  border-radius: 8px !important;
}
```
