### ISSUE TITLE
[Feature]: allow modify public path on fly

### ISSUE THREAD

**Issue by xc2** [web-infra-dev/rsbuild#1036]
### What problem does this feature solve?

as the html plugin allows us to modify the public path for initial js/css files, i usually create an preEntry for js chunks to make the public path being used inside js chunks too. just like this

```typescript
if (typeof window !== 'undefined' && window.__CONFIG__?.publicPath) {
  __webpack_public_path__ = window.__CONFIG__?.publicPath;
}
```

maybe rsbuild could make it happen by default.

### What does the proposed API look like?

have no idea at the moment

**Comment by chenjiahan** [comment]
I have some questions for this:

- Where does this `__CONFIG__` come from?
- Is its content dynamic?

**Comment by xc2** [comment]
`__CONFIG__` could be anything else like `__XXX__`.

my build setup is like:

```yaml
public_path: https://cdn1.example.com/
pre_entry: ./src/public-path.ts
entry: ./src/index.ts
html:
- public_path: https://cdn1-us.example.com/
  filename: us.html
- public_path: https://cdn1-hk.example.com/
  filename: hk.html
```

template:

```ejs
<script>window.__XXX__ = <%= JSON.stringify(htmlWebpackPlugin.options.publicPath) %></script>
```

pre entry:

```ts
// ./src/public-path.ts
if (typeof window !== 'undefined' && window.__XXX__) {
  __webpack_public_path__ = window.__XXX__;
}
```

if I don't add the pre entry, when I open us.html, initial js chunks are loaded from "cdn1-us" while async js chunks or other dynamic assets are all loaded from the default public path which is "cdn1".

i'm not sure i should tell it dynamic or static.

the only requirements is the reference name `__XXX__` should be same in the template and the pre entry file. ( i used to use `<meta>` instead of global variable.)

more, i never modify the value of `window.__XXX__` at runtime.
