### ISSUE TITLE
[Bug]:   ⚠ ModuleWarning: resolve-url-loader: webpack misconfiguration   │   webpack or the upstream loader did not supply a source-map

### ISSUE THREAD

**Issue by bosens-China** [web-infra-dev/rsbuild#3002]
### Version

```sh
System:
    OS: macOS 14.5
    CPU: (8) arm64 Apple M1 Pro
    Memory: 102.23 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Browsers:
    Chrome: 126.0.6478.183
    Safari: 17.5
  npmPackages:
    @rsbuild/core: ^1.0.1-beta.4 => 1.0.1-beta.4 
    @rsbuild/plugin-babel: ^1.0.1-beta.4 => 1.0.1-beta.4 
    @rsbuild/plugin-less: ^1.0.1-beta.4 => 1.0.1-beta.4 
    @rsbuild/plugin-node-polyfill: ^1.0.3 => 1.0.3 
    @rsbuild/plugin-sass: ^1.0.1-beta.4 => 1.0.1-beta.4 
    @rsbuild/plugin-svgr: ^1.0.1-beta.4 => 1.0.1-beta.4 
    @rsbuild/plugin-vue: ^1.0.1-beta.4 => 1.0.1-beta.4 
    @rsbuild/plugin-vue2: ^1.0.1-beta.4 => 1.0.1-beta.4 
    @rsbuild/plugin-vue2-jsx: ^1.0.1-beta.4 => 1.0.1-beta.4
```

### Details

迁移vuecli项目的过程中，发现scss文件提示这个错误
``` css
.spinning {
    height: 350px;
    position: absolute;
    left: 0;
    top: 0;
    width: 100%;
    text-align: center;
    line-height: 350px;
    z-index: 999;
}

#components-layout-demo-custom-trigger .trigger {
    cursor: pointer;
    transition: color 0.3s;
}

#components-layout-demo-custom-trigger .trigger:hover {
    color: $primary-color;
}

.my-layout {
    height: 100%;

    .layout-header {
        background: #fff;
        padding: 0;
        height: 48px;
        position: fixed;
        right: 0;
        top: 0;
    }

    .breadcrumb {
        height: 30px;
        padding: 5px 0 0 24px;
        background: #F7F8FA;
    }

    .ant-menu-dark,
    .ant-menu-dark .ant-menu-sub {
        background: #162c64;
    }

    .ant-menu-dark .ant-menu-inline.ant-menu-sub {
        background: #162c64;
        box-shadow: none !important;
    }


    .ant-menu-item .anticon,
    .ant-menu-submenu-title .anticon {
        min-width: 24px;
        font-size: 24px;
        transform: scale(0.67);
        vertical-align: middle;
        margin-top: -2px;
        margin-right: 5px;
    }

    .ant-menu-inline-collapsed>.ant-menu-item .anticon,

    .ant-menu-inline-collapsed>.ant-menu-item-group>.ant-menu-item-group-list>.ant-menu-item .anticon,

    .ant-menu-inline-collapsed>.ant-menu-item-group>.ant-menu-item-group-list>.ant-menu-submenu>.ant-menu-submenu-title .anticon,

    .ant-menu-inline-collapsed>.ant-menu-submenu>.ant-menu-submenu-title .anticon {
        min-width: 24px;
        font-size: 24px;
        line-height: 56px;
        transform: scale(1);
    }

    .ant-menu-inline-collapsed>.ant-menu-item,
    .ant-menu-inline-collapsed>.ant-menu-item-group>.ant-menu-item-group-list>.ant-menu-item,

    .ant-menu-inline-collapsed>.ant-menu-item-group>.ant-menu-item-group-list>.ant-menu-submenu>.ant-menu-submenu-title,

    .ant-menu-inline-collapsed>.ant-menu-submenu>.ant-menu-submenu-title {
        text-align: center;
        padding: 0 !important;
        height: 56px;
        min-width: 24px;
    }

    .layout-main {
        height: 100%;
        /* min-width: 1126px; */
        /* overflow-x: auto!important;*/
    }

    .ant-layout {
        background: #F7F8FA;
    }
}


.trans {
    transition: all 0.2s;
}


.layout-inner {
    padding-top: 48px;
    width: 100%;
    height: 100%;
}

.layout-bg {
    background: #F7F8FA;
}

.layout-content {
    position: relative;
    height: calc(100% - 30px);
}

.my-layout-collapsed {

    .ant-menu-dark .ant-menu-item:hover,
    .ant-menu-dark .ant-menu-item-active,
    .ant-menu-dark .ant-menu-submenu-active,
    .ant-menu-dark .ant-menu-submenu-open,
    .ant-menu-dark .ant-menu-submenu-selected,
    .ant-menu-dark .ant-menu-submenu-title:hover {
        background-color: $suncn-blue-400 !important;
        color: #fff !important;
    }
}

.folder-nav:hover {
    color: #fff !important;
}

.ant-menu-inline-collapsed {
    width: 57px !important;
}

.left-navlist::-webkit-scrollbar {
    width: 6px;
    /*对垂直流动条有效*/
    height: 6px;
    /*对水平流动条有效*/
}

/*定义滚动条的轨道颜色、内阴影及圆角*/
.left-navlist::-webkit-scrollbar-track {
    /*-webkit-box-shadow: inset 0 0 6px rgba(0, 0, 0, 0.3);*/
    background-color: transparent;
    border-radius: 3px;
}

/*定义滑块颜色、内阴影及圆角*/
.left-navlist::-webkit-scrollbar-thumb {
    border-radius: 3px;
    /* -webkit-box-shadow: inset 0 0 6px rgba(0, 0, 0, 0.3); */
    background-color: rgba(213, 225, 255, .2);
}

/*定义两端按钮的样式*/
.left-navlist::-webkit-scrollbar-button {
    background-color: transparent;
}

/*定义右下角汇合处的样式*/
.left-navlist::-webkit-scrollbar-corner {
    background: transparent;
}
```

报错信息
``` sh
File: /Users/yliu/Desktop/job/jcnl-admin/src/layout/style.scss:1:1
  ⚠ ModuleWarning: resolve-url-loader: webpack misconfiguration
  │   webpack or the upstream loader did not supply a source-map (from: /Users/yliu/Desktop/job/jcnl-admin/node_modules/@rsbuild/plugin-sass/compiled/resolve-url-loader/index.js??clonedRuleSet-81.use[3])
```

关闭map
``` js
    pluginSass({
      sassLoaderOptions: {
        sourceMap: false,
        additionalData:
          '@import "@/styles/variables.scss";@import "@/styles/mixin.scss";', // @import "@/styles/localIcon.scss";
      },
    }),
```
提示
File: /Users/yliu/Desktop/job/jcnl-admin/src/styles/index.scss:1:1
  × Module build failed:
  ╰─▶   × Error: HookWebpackError:   × Module build failed:
        │   ╰─▶   × Error: resolve-url-loader: error processing CSS
        │         │   a valid source-map is not present (ensure preceding loaders output a source-map)

正确做法是什么？

### Reproduce link

none

### Reproduce Steps

正常输出
